import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NavBar from "../Components/NavBar/NavBar";
import styles from "../styles/Home.module.css";
import travel from "../assets/Images/travel.png";
import Buttons from "../Components/Buttons/Buttons";
import youtube from "../assets/Icons/youtube.png";
import Card from "../Components/CardComponent/Card";
import weather from "../assets/Images/weather.png";
import airplane from "../assets/Icons/airplane.png";
import event from "../assets/Icons/dj.png";
import customization from "../assets/Icons/feature.png";
import DestinationCard from "../Components/DestinationCard/DestinationCard";
import rom from "../assets/Images/rom.avif";
import kite from "../assets/Images/kite.png";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>travel agency website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className={styles.contentandimagecontainer}>
        <div className={styles.contentcontainer}>
          <h4 className={styles.title}>BEST DESTINATIONS AROUND THE WORLD</h4>
          <h1 className={styles.subtitle}>
            Travel,enjoy <br />
            and live a new <br />
            and full life.
          </h1>
          <p className={styles.paragraph}>
            Travelling is an amazing way to learn a lot of things in life.{" "}
            <br />A lot of people around the world travel every year to many
            places.
          </p>
          <div className={styles.bodybuttoncontainer}>
            <Buttons className="more-btn" text="Find out more" />
            <div className={styles.youtubeiconcontainer}>
              <Image src={youtube}></Image>
              <h6 className={styles.playdemotext}>Play Demo</h6>
            </div>
          </div>
        </div>

        <div className={styles.imagecontainer}>
          <Image src={travel} width={700} height={500}></Image>
        </div>
      </div>
      <div className={styles.subcontainer}>
        <h4 className={styles.categorytext}>CATEGORY</h4>
        <h1 className={styles.subcategorytxt}>We Offer Best Services</h1>
      </div>
      <div className={styles.maincardcontainer}>
        <Card
          img={weather}
          width={80}
          height={85}
          title="Calculated Weather"
          paragraph="Lorem, ipsum dolor sit amet
         consectetur adipisicing elit."
        />
        <Card
          img={airplane}
          width={80}
          height={85}
          title="Best Flights"
          paragraph="Lorem, ipsum dolor sit amet
         consectetur adipisicing elit."
        />
        <Card
          img={event}
          width={80}
          height={85}
          title="Local Events"
          paragraph="Lorem, ipsum dolor sit amet
         consectetur adipisicing elit."
        />
        <Card
          img={customization}
          width={80}
          height={85}
          title="Customization"
          paragraph="Lorem, ipsum dolor sit amet
         consectetur adipisicing elit."
        />
      </div>
      <div className={styles.sectiontitlecontainer}>
        <h4 className={styles.categorytext}>Top Selling</h4>
        <h1 className={styles.subcategorytxt}>Top Destinations</h1>
      </div>
      <div className={styles.destinationcardcontainer}>
        <DestinationCard
          image={rom}
          width={170}
          height={200}
          title="Rome,Italy"
          rate="$52.5k"
          days="10 Days Trip"
          kiteimg={kite}
          widths={25}
          heights={25}
        />
      </div>
    </div>
  );
};

export default Home;
